### ISSUE TITLE
레시피 스텝 9: 후추 뿌려 음식 내기

### ISSUE THREAD

**Issue by justinyoo** [justinyoo/Seasons-of-Serverless#12]
* 형식: HTTP API / POST 메소드
* 서비스: 애저 펑션
* 요청 개체:

```
{
  "pepper": true/false
}
```

* 응답 개체:

```
{
  "tteokgukImageUrl": "https://xxxx/xxx.png"
}
```

* 처리 방식:
  * `pepper` 값에 따라 후추를 추가하는 메소드 구성
  * 옵션 1: 구글 이미지 검색 결과로 랜덤하게 떡국 이미지 URL 반환
  * 옵션 2: 미리 떡국 이미지 셋을 애저 블롭 저장소에 저장해 놓고 그 중 하나를 랜덤하게 반환

* 유의사항
  * 스텝 하나당 애저 펑션 인스턴스 하나입니다
  * 듀어러블 펑션의 타이머 기능을 이용해 보세요
  * 옵션 1 혹은 2 어떤 것을 선택할지는 미리 결정해 주세요.

**Comment by roharon** [comment]
스텝9 맡겠습니다

**Comment by roharon** [comment]
떡국 이미지 반환 방식은 옵션2(블롭저장소) 사용합니다 :)
