### ISSUE TITLE
배포 시 storageaccount 중복으로 인한 "The storage account named stsoskrc is already taken"  오류 반환

### ISSUE THREAD

**Issue by hongman** [justinyoo/Seasons-of-Serverless#29]
**Describe the bug**
현재 템플릿 사용시 StorageAccount 이름이 자동으로 stsoskrc으로 만들어지게 되어있습니다.

![image](https://user-images.githubusercontent.com/8444994/100626359-13b2ce00-3369-11eb-9a74-e8c3bace34c1.png)

이유는 [azuredeploy.json](https://github.com/justinyoo/Seasons-of-Serverless/blob/solution/solutions/2020-12-21/Resources/azuredeploy.json)의 42~45줄의 
`  "storage": {
      "name": "[format(variables('metadata').shortName, 'st')]",
      "location": "[parameters('location')]",
      "sku": "[parameters('storageAccountSku')]"
    },` 
에서 이름 규칙이 st +azuredeploy.params.json 내의 sos + locationCode(krc - KoreaCentral) 이라, 이미 존재하는 이름이라고 오류가 반환되는 것 같습니다.

**Expected behavior**
저 같은 경우엔 azuredeploy.params.json 의 sos를 soshongman 이런식으로 바꾸어 storageAccount가 'stsoshongmankrc' 로 생성되며 배포는 했는데, 어떤 방법이 좋은 수정 방법일지 몰라 이슈 남기게 되었습니다.

**Comment by justinyoo** [comment]
CLI를 사용할 때 파라미터 파일을 사용해도 되지만 `name=${{ secrets.RESOURCE_NAME }} locationCode=${{ secrets.LOCATION_CODE }} functionAppTimezone="${{ secrets.TIMEZONE }}" index=1 functionAppWorkerRuntime=python` 같은 식으로 모든 파라미터를 직접 입력해 주세요. 그러면 컨플릭이 나지 않습니다.

스토리지 어카운트 경우는 도메인 주소로 사용이 되기 때문에 누가 선점했을 경우 위와 같은 에러가 나욥.

**Comment by justinyoo** [comment]
실제 배포 파이프라인을 보면 아실 수 있을 거예요

https://github.com/justinyoo/Seasons-of-Serverless/blob/1f6229c63ae041187a01ba8f272e69c4f92ad4d9/.github/workflows/main.yaml#L57

**Comment by hongman** [comment]
오오.. 아무 생각 없이 [link](https://github.com/justinyoo/Seasons-of-Serverless/blob/solution/Dec-21-2020.md?fbclid=IwAR20GBiikgCqhaVOmu1no06XfiLFn6TTJVU0v7I9c5Z6j7tmkBKOOec3Wig#ready-to-submit-a-solution-to-this-challenge-heres-how) 보고 하다 그렇게 되었는데 제가 짧게 보았네요 ㅠㅠ

**Comment by justinyoo** [comment]
화이팅!
