### ISSUE TITLE
레시피 스텝 1: 가래떡 썰기 + 물에 불리기

### ISSUE THREAD

**Issue by justinyoo** [justinyoo/Seasons-of-Serverless#4]
* 형식: HTTP API / POST 메소드
* 서비스: 애저 듀어러블 펑션
* 요청 개체:

```
{
  "boughtSlicedGaraetteok": true/false,
  "timeToSoakInMinutes": 30
}
```

* 응답 개체:

```
{
  "completed": true/false
}
```

* 처리 방식:
  * `boughtSlicedGaraetteok` 값에 따라 가래떡을 물에 불릴지, 썰지 결정한다
  * `timeToSoakInMinutes` 값 동안 가래떡을 물에 불린다
  * 가래떡을 물에 불린 후 불린 정도 체크를 한다 (`true`/`false`). 체크 결과는 랜덤. 만약 아직 안 불었으면 1분 후 다시 체크한다.
  * 가래떡을 썰 경우, 다 써는 시간도 불리는 시간과 동일하다고 가정한다. 다 썰었는지 체크를 한다 (`true`/`false`). 체크 결과는 랜덤. 만약 아직 안 불었으면 1분 후 다시 체크한다.
  * 가래떡이 다 불었거나 가래떡을 다 썰었을 경우, 응답 개체를 `true`로 반환한다

* 유의사항
  * 스텝 하나당 애저 펑션 인스턴스 하나입니다
  * 듀어러블 펑션의 타이머 기능을 이용해 보세요

**Comment by roharon** [comment]
스텝1 제가 맡겠습니다~!
