### ISSUE TITLE
레시피 스텝 2: 파 썰기

### ISSUE THREAD

**Issue by justinyoo** [justinyoo/Seasons-of-Serverless#5]
* 형식: HTTP API / POST 메소드
* 서비스: 애저 듀어러블 펑션
* 요청 개체:

```
{
  "timeToSliceInMinutes": 5
}
```

* 응답 개체:

```
{
  "completed": true/false
}
```

* 처리 방식:
  * `timeToSliceInMinutes` 값 동안 파를 썬다
  * 파를 다 썰었는지 체크를 한다 (`true`/`false`). 체크 결과는 랜덤. 만약 아직 안 불었으면 1분 후 다시 체크한다.
  * 파를 다 썰었을 경우, 응답 개체를 `true`로 반환한다

* 유의사항
  * 스텝 하나당 애저 펑션 인스턴스 하나입니다
  * 듀어러블 펑션의 타이머 기능을 이용해 보세요

**Comment by hongman** [comment]
제가 하겠습니다!
