### ISSUE TITLE
레시피 스텝 3: 소고기 볶기

### ISSUE THREAD

**Issue by justinyoo** [justinyoo/Seasons-of-Serverless#6]
* 형식: HTTP API / POST 메소드
* 서비스: 애저 듀어러블 펑션
* 요청 개체:

```
{
  "timeToStirFryInMinutes": 8
}
```

* 응답 개체:

```
{
  "completed": true/false
}
```

* 처리 방식:
  * `timeToStirFryInMinutes` 값 동안 고기를 볶는다
  * 고기를 다 볶았는지 체크를 한다 (`true`/`false`). 체크 결과는 랜덤. 만약 아직 안 불었으면 1분 후 다시 체크한다.
  * 고기를 다 볶았을 경우, 응답 개체를 `true`로 반환한다

* 유의사항
  * 스텝 하나당 애저 펑션 인스턴스 하나입니다
  * 듀어러블 펑션의 타이머 기능을 이용해 보세요

**Comment by roharon** [comment]
스텝3 맡겠습니다 :-)
