### ISSUE TITLE
레시피 스텝 4: 재료 물에 넣고 끓이기

### ISSUE THREAD

**Issue by justinyoo** [justinyoo/Seasons-of-Serverless#7]
* 형식: HTTP API / POST 메소드
* 서비스: 애저 듀어러블 펑션
* 요청 개체:

```
{
  "timeToBoilInMinutes": 30
}
```

* 응답 개체:

```
{
  "boiled": true/false
}
```

* 처리 방식:
  * `timeToBoilInMinutes` 값 동안 재료를 끓인다
  * 재료가 다 끓었는지 체크를 한다 (`true`/`false`). 체크 결과는 랜덤. 만약 아직 덜 끓었으면 1분 후 다시 체크한다.
  * 재료가 다 끓었을 경우, 응답 개체를 `true`로 반환한다

* 유의사항
  * 스텝 하나당 애저 펑션 인스턴스 하나입니다
  * 듀어러블 펑션의 타이머 기능을 이용해 보세요

**Comment by u0jin** [comment]
제가 할게요~!

**Comment by u0jin** [comment]
**Add : Step 4 durable functions** #16
