### ISSUE TITLE
레시피 스텝 5: 끓는 동안 거품 제거

### ISSUE THREAD

**Issue by justinyoo** [justinyoo/Seasons-of-Serverless#8]
* 형식: HTTP API / POST 메소드
* 서비스: 애저 펑션
* 요청 개체:

```
{
  "bubbleAppeared": true/false
}
```

* 응답 개체:

```
{
  "removed": true/false
}
```

* 처리 방식:
  * `bubbleAppeared` 값이 `true`이면 거품을 제거한다
  * 거품을 제거했을 경우 경우, 응답 개체를 `true`로 반환한다

**제약사항**: #7 (레시피 스텝 4: 재료 물에 넣고 끓이기)가 진행되는 동안 주기적으로 발생하는 이벤트임. 파워 앱 상에서 주기적으로 발생하는 이벤트로 구성할 것

* 유의사항
  * 스텝 하나당 애저 펑션 인스턴스 하나입니다

**Comment by hongman** [comment]
제가 하겠습니다!
