### ISSUE TITLE
레시피 스텝 6: 계란 풀기

### ISSUE THREAD

**Issue by justinyoo** [justinyoo/Seasons-of-Serverless#9]
* 형식: HTTP API / POST 메소드
* 서비스: 애저 듀어러블 펑션
* 요청 개체:
  * N/A

* 응답 개체:

```
{
  "completed": true/false
}
```

* 처리 방식:
  * 요청 받은 1분 후 응답 개체를 `true`로 반환한다

* 유의사항
  * 스텝 하나당 애저 펑션 인스턴스 하나입니다
  * 듀어러블 펑션의 타이머 기능을 이용해 보세요

**Comment by u0jin** [comment]
제가 할게요~!!

**Comment by u0jin** [comment]
**Add : Step 6 durable functions** #16
